### ISSUE TITLE
smart refreshes with logged last refresh

### ISSUE THREAD

**Issue by CuddleBear92** [fake-name/xA-Scraper#49]
at the moment the refresh/check for new files system does work on a timer from the startup of the script it seems. this can work on a server for sure but limits it to be on 24/7 or get stuck waiting for the timer to pop.
if the program logged the time and date each time each of the sites was refreshed with content then it can more easily be used on machines that isnt on all the time. (and dont want it to update every hour or whatever)

so say if you have a refresh time on 12 hours or 24 hours for example. when the scraper starts up it should check the time of the last check and if its more than the set time it will start a check right away.

this way you are not limited by either have a machine on at all times that checks once a day. and you are not forced to have a short check timer to get the content quickly after the start of the scraper. 

if i say havent had the machine on for a while and turned on the scraper then it should try to get new content asap. not wait 24 hours or whatever time i had. since longer timers like that makes sense in the long run of things.

**Comment by fake-name** [comment]
The scheduling isn't actually bound to the startup, it's tied to a intervals [derived from a specific date](https://github.com/fake-name/xA-Scraper/blob/master/main.py#L106).

THis was mostly done because having all the scrapers fire every time I started the scheduler was extremely annoying when restarting the scraper multiple times in a short period of time, principally from when I was doing development on the web stuff.

Realistically, the better solution here would probably be to move the scheduling into the database. APScheduler (which I'm using) can already do this. That would allow it to track "missed" executions, so if you have the scraper off for a few days, it'd try to run the fetches it missed over those few days the next restart.

**Comment by CuddleBear92** [comment]
I just find that a lot of the times I start the script even with just a 6 hour time I will have to wait hours before it starts updating. This is after the script have been off for maybe days which isn't how it should be in my eyes. 

Maybe an manual forced refresh button in the web ui could be a workaround. 

But the script isn't turned on that often. Normally rings for days and days at a time at a minimum. But an option to maybe run on startup could be a thing.

**Comment by fake-name** [comment]
Is there some reason `python -m manage fetch` doesn't work?

You can run specific scrapers, or the whole affair manually via the management interface (`python -m manage`).
