### ISSUE TITLE
Tumblr authentication problem

### ISSUE THREAD

**Issue by omgold** [fake-name/xA-Scraper#54]
I cannot get the tumblr plugin to work. I acquired a consumer_key, consumer_secret, access_token and access_token_secret using this method:

https://wordpress.stackexchange.com/a/239873

But the scraper only says this

Main.TumblrGet.StatusMgr - INFO - Have authentication: False
Main.TumblrGet.StatusMgr - INFO - Do not have login cookie. Retreiving one now.
Main.TumblrGet.StatusMgr - INFO - Login attempt status = (True, 'Logged In').
Main.TumblrGet.StatusMgr - INFO - Have authentication: False
Main.TumblrGet.StatusMgr - CRITICAL - Failed to download cookie! Exiting!

What is wrong here?

**Comment by fake-name** [comment]
I think the issue is your auth token is not valid.

The output is kind of confusing because I left a bunch of dumb stuff in there from porting it from another site.

Fundamentally, what you're seeing in that output is that the tumblr auth interface things your token *looks* OK, but when it tries to actually access tumblr, it's failing.

In this case, the scraper uses [TumblPy](https://github.com/michaelhelmick/python-tumblpy) for accessing tumblr, so you should probably use their example to generate a correct auth key set.

Download their example [here](https://github.com/michaelhelmick/python-tumblpy/blob/master/examples/example.py) (click the "raw" link), and run it via `python3 example.py`.

It'll interactively ask you for your tumblr creds, provide you with a OAuth URL, and then print the relevant secret key stuff.

**Comment by omgold** [comment]
Ah, didn't know that there was a guide from TumblPy. 

In any case I figured it out. It is not about the authentication itself (this would produce an exception from TumblPy), but rather from the checkCookie() method in tumblrScape. It tries to find the username, but the API send it always lowercase. So it will only work when the username in settings.py is also all lowercase.

**Comment by fake-name** [comment]
Check cookie doesn't manipulate your username at all, but it is case sensitive.

What do you mean?

**Comment by fake-name** [comment]
The original issue (case mismatch) should also be fixed now. I don't know what would happen if tumblr allows multiple identical usernames with differing case (I guess they don't?).
