### ISSUE TITLE
Incomplete patreon downloads

### ISSUE THREAD

**Issue by reketeee** [fake-name/xA-Scraper#61]
Hi,

I've noticed that some posts are incomplete, only the first image is downloaded.
Like this one: https://imgur.com/EMKFwUY

But in others, all images are downloaded correctly.
Like this one: https://imgur.com/Fui1E7d

The only difference i see is that in one of them, images appears as attachments.

Could you check it?

Thanks :)

**Comment by ImportTaste** [comment]
@fake-name adding /zip to the end of an imgur url is typically an easy way to get an entire album. However it won't have a good default filename and the images contained within are prefixed with their sequence order, which makes them get easily mixed up with other albums if you extract them all into the same directory.

**Comment by reketeee** [comment]
Hi,

I think i didn't explain correctly.
Those imgur links are screenshots i did for trying to show the problem with certains patreon posts.

Imgur isn't the problem ;)

Sorry if i don't explain correctly, english isn't my main language.

**Comment by fake-name** [comment]
Hmmm, it seems patreon has a new way for attaching images.

**Comment by fake-name** [comment]
Ok, this seems to be resolved. I basically kind of made some semi-educated guesses about how patreon's API works internally, and it turns out they were either correct, or there's a patreon bug that made them seem correct. 

Please let me know if you see other content that's not working. Aside from enjoying the content, I don't inspect the downloads for everyone I back that closely, so I missed this change. Thanks!
