### ISSUE TITLE
fAGet: New website design

### ISSUE THREAD

**Issue by ImportTaste** [fake-name/xA-Scraper#90]
FA's new design is finally done, and it's actually quite an improvement. Unfortunately I don't think it plays nice with xA-Scraper. You can use the Classic theme in the meantime, but it's bound to account and there's no special cookie value for it.

One workaround is to register a side account that uses the classic theme to scrape with.

**Comment by fake-name** [comment]
Whoops, quoted the wrong URL. Any ways, this is fixed in https://github.com/fake-name/xA-Scraper/commit/bebce80878656c8d8591f46e6b6692c61448f08c

Note that there may be some gallery formats (videos?) that are still broken. I'm running tests now.

Also, you may need to update your requirements. I did some patching in at least WebRequest that I now depend on, but the changes are in pypi, so `pip install -r requirements.txt` should fetch everything needed.
