### ISSUE TITLE
FreeBSD chromedriver-binary issue.

### ISSUE THREAD

**Issue by LandMineHare** [fake-name/xA-Scraper#94]
So far, I've managed to get everything installed and working out of all the requirements, and  run_scrape.sh works up until this little ditty pops up.

`> Building wheels for collected packages: chromedriver-binary`
`> Building wheel for chromedriver-binary (setup.py) ... error`

I've got chromium and the chromedriver unit installed, and chrome driver works when called anywhere, but I can't for the life of me find anywhere in the scripts that references chromedriver-binary to change it to just chromedriver.

Was hoping someone, anyone, else had luck getting this to work in a FreeBSD jail, or can point me where to look to fix it.

**Comment by fake-name** [comment]
That's interesting. FWIW, FreeBSD is **super** out of my tested scope of OSes.

Anyways, the issue here is:

 - `xa-Scraper` depends on [`webrequest`](https://pypi.org/project/WebRequest/)
 - `webrequest` [depends](https://github.com/fake-name/WebRequest/blob/master/requirements.txt#L8) on *the python package* [`chromedriver-binary`](https://pypi.org/project/chromedriver-binary/)

So basically https://pypi.org/project/chromedriver-binary/ doesn't work on FreeBSD, apparently. 

Realistically, you don't actually *need* chromedriver unless you're using the selenium chrome interface in `webrequest`, and I've been trying to move off that to [my own chrome interface](https://github.com/fake-name/ChromeController), mostly because selenium has a bunch of really, really stupid design decisions that make stuff really difficult. You should be able to clone webrequest, remove the dependency from the requirements file, and then install it manually. It should work fine.
